perf(uhash): Speed up uhash calculations
snyk/snyk-cpp-plugin pull request #43
Opened 2021-10-07 10:20 UTC by akerud

uhash is now faster than dubhash, and almost as fast as half-dubhash.

- [x] Ready for review
- [ ] Follows CONTRIBUTING rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

tldr: makes uhash faster

we found that uhash was significantly slower than expected.
uhash does less work than dubhash, and should therefore be faster.
now it is.

#### Where should the reviewer start?

at the top, and then read downwards

#### How should this be manually tested?

this is tested with unit tests

#### Any background context you want to provide?

before delopying uhash we need to make sure the performance is as expected

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2021-10-07 10:27 UTC, dekelund requested changes
Maybe add some unit tests?

2021-10-07 11:22 UTC, robguinness-snyk commented
> Maybe add some unit tests?

I'll let @akerud elaborate, but the existing unit tests should cover this change, unless you meant some kind of performance test.

Perhaps one thing to make the commit more clear in the git history is `refactor(uhash): Speed up uhash calculations` instead of `feat(uhash): Speed up uhash calculations`.

2021-10-07 11:27 UTC, ekbsnyk approved these changes

2021-10-07 11:32 UTC, akerud commented
> Maybe add some unit tests?

i think tests/uhash.test.ts covers it (has unit tests for generating different kinds of uhashes)

2021-10-08 07:43 UTC, dekelund approved these changes

2021-10-08 07:51 UTC, merged

2021-10-08 07:55 UTC, snyksec commented
:tada: This PR is included in version 2.12.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/snyk-cpp-plugin/v/2.12.2)
- [GitHub release](https://github.com/snyk/snyk-cpp-plugin/releases/tag/v2.12.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: